
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: delete older package-lock-json Dependencies
          command: rm -rf package-lock.json node_modules 
      - run:
          name: Setup Dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: Run Test 
          command: |
            npm test
# deploy:
#     docker:
#       - image: buildpack-deps:trusty          
#     steps:
#       - checkout
#       - run:
#           name: Deploy Master to HEROKU
          # command: git push https://heroku:3274df71-ac24-4dc4-99a1-26849cfafe33@git.heroku.com/infinite-waters-48339.git master
          

workflows:         
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master


